#pragma once

// ALL WM_USER messages are to be declared here *after* 'WM_FIRST_EMULE_USER_MSG'
enum EUserWndMessages
{
	// *) Do *NOT* place any message *before* WM_FIRST_EMULE_USER_MSG !!
	// *) Do *NOT* use any WM_USER messages in the range WM_USER - WM_USER+0x104 !! (AsyncSocketEx)
	UM_FIRST_EMULE_USER_MSG = (WM_USER + 0x110 + 1)

	// Taskbar
	, UM_TASKBARNOTIFIERCLICKED //+2
	, UM_TRAY_ICON_NOTIFY_MESSAGE

	// Web Server
	, WEB_GUI_INTERACTION //+5
	, WEB_CLEAR_COMPLETED
	, WEB_FILE_RENAME
	, WEB_ADDDOWNLOADS
	, WEB_CATPRIO
	, WEB_ADDREMOVEFRIEND

	// PC
	, UM_PEERCACHE_RESPONSE //+10 - defunct

	// ClosableTabCtrl
	, UM_CLOSETAB	//+13
	, UM_QUERYTAB
	, UM_DBLCLICKTAB

	// Colour popup
	, UM_CPN_SELCHANGE //+16
	, UM_CPN_DROPDOWN
	, UM_CPN_CLOSEUP
	, UM_CPN_SELENDOK
	, UM_CPN_SELENDCANCEL

	, UM_MEDIA_INFO_RESULT //+21
	, UM_ITEMSTATECHANGED
	, UM_SPN_SIZED
	, UM_TABMOVED
	, UM_TREEOPTSCTRL_NOTIFY
	, UM_DATA_CHANGED
	, UM_OSCOPEPOSITION
	, UM_DELAYED_EVALUATE
	, UM_AUTO_RELOAD_SHARED_FILES
	, UM_AICH_HASHING_COUNT_CHANGED
	, UM_PIPE_API_COMMAND

	// UPnP
	, UM_UPNP_RESULT //+32
	, UM_WSAPOLL_UDP_SOCKET
	, UM_PARTFILE_DISPLAY_UPDATE
	, UM_CLIENT_DISPLAY_UPDATE
	, UM_SEARCHLIST_VIEW_REFRESH

	// TreeOptionsCtrl
	, WM_TOC_SETFOCUS_TO_CHILD //+33
	, WM_TOC_REPOSITION_CHILD_CONTROL //+34
};
